import Head from 'next/head';
import LandingPage from '../components/landingPage/LandingPage';

export default function Home() {
	return (
		<>
			<Head>
				<title>MBTI Channel</title>
				<meta name='description' content='Generated by MBTI Channel' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<LandingPage />
		</>
	);
}
