import Head from 'next/head';
import Header from '../src/components/Header';

export default function Home() {
	return (
		<>
			<Head>
				<title>MBTI Channel</title>
				<meta name='description' content='Generated by MBTI Channel' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header /> {/* landingPage로 렌더링하기 */}
		</>
	);
}
